#index:
#    path: /
#    controller: App\Controller\DefaultController::index
doc_shortcut:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'course_index'